---
- hosts: javaserver
  become: all
  tasks:
    - include_tasks: createfileplaybook.yml

    - name: i want to install apache2 on node server
      apt:
        name: apache2
        state: present
