---
- hosts: all
  become: yes
  tasks: 

   - name: install tree
     apt: 
       name: tree
       state: present
     tags: mytree

   - name: install git
     apt:
       name: gitt
       state: present
     tags: mygit
     ignore_errors: yes

   - name: install wget
     apt:
       name: wget
       state: present
     tags: mywget
